
services:
  wxfdashboardsaio_grafana:
    container_name: wxfdashboardsaio_grafana
    environment:
      TZ: ${TZ}
    image: maxo99/weatherflow-grafana:latest
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: always
    volumes:
    - wxfdashboardsaio-grafana-data:/var/lib/grafana
    # - ./logs:/var/log/grafana
  wxfdashboardsaio_influxdb:
    container_name: wxfdashboardsaio_influxdb
    environment:
      TZ: ${TZ}
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_DB: ${INFLUXDB_DB_NAME}
      INFLUXDB_HTTP_LOG_ENABLED: "true"
      INFLUXDB_LOGGING_FORMAT: json
      INFLUXDB_LOGGING_LEVEL: DEBUG
      INFLUXDB_MONITOR_STORE_DATABASE: _internal
      INFLUXDB_MONITOR_STORE_ENABLED: "true"
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_USER: weatherflow
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
    image: influxdb:1.8
    ports:
    - protocol: tcp
      published: 8086
      target: 8086
    restart: always
    volumes:
    - wxfdashboardsaio-influxdb-data:/var/lib/influxdb:rw
  wxfdashboardsaio-collector:
    container_name: maxo99-weatherflow-collector-ef948828
    environment:
      TZ: America/New_York
      WEATHERFLOW_COLLECTOR_DEBUG: "true"
      WEATHERFLOW_COLLECTOR_DEBUG_CURL: "true"
      WEATHERFLOW_COLLECTOR_DISABLE_HEALTH_CHECK: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_HOST_PERFORMANCE: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_LOCAL_UDP: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_FORECAST: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_REST: "true"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_SOCKET: "false"
      WEATHERFLOW_COLLECTOR_HEALTHCHECK: "true"
      WEATHERFLOW_COLLECTOR_HOST_HOSTNAME: wxfdashboardsaio_collector
      # Environment variables for InfluxDB connection
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://wxfdashboardsaio_influxdb:8086
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_DATABASE: ${INFLUXDB_DB_NAME}
      WEATHERFLOW_COLLECTOR_API_TOKEN: ${WEATHERFLOW_COLLECTOR_TOKEN}
      WEATHERFLOW_COLLECTOR_INFLUXDB_ORG: 1
      WEATHERFLOW_COLLECTOR_INFLUXDB_BUCKET: weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_TOKEN: ${INFLUXDB_ADMIN_PASSWORD}
      WEATHERFLOW_COLLECTOR_LOGGER_FILE_ENABLED: "true"
      WEATHERFLOW_COLLECTOR_EXPORT_COLLECTOR_STALE_SEGMENT_DAYS: 1
    restart: always
    depends_on:
      - "wxfdashboardsaio_influxdb"
    image: maxo99/weatherflow-collector:latest
    ports:
    - protocol: udp
      published: 50222
      target: 50222
volumes:
  wxfdashboardsaio-grafana-data:   
  wxfdashboardsaio-influxdb-data: 
