apiVersion: 1
datasources:
  - name: Garmin-InfluxDB
    uid: garmin_influxdb
    type: influxdb
    url: "http://maxo99-influxdb:8086/"
    database: GarminStats
    editable: true
    basicAuth: false
